name: Cargo Build & Test

on:
  push:
    branches: ["main"]
    paths:
      - frost-uniffi-sdk
      - uniffi-bindgen
      - Cargo.toml
  pull_request:
      branches: ["main"]
      
      paths:
        - frost-uniffi-sdk
        - uniffi-bindgen
        - Cargo.toml

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    if: ${{ ! startsWith(github.event.pull_request.head.ref, 'release-') }}
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --all-features
      - run: cargo test --verbose