on:
    push:
      paths:
        - frost-uniffi-sdk
        - uniffi-bindgen
        - Cargo.toml
    pull_request:
      paths:
        - frost-uniffi-sdk
        - uniffi-bindgen
        - Cargo.toml
      branches-ignore: 
        - "release-*.*.*"
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-features