name: Swift Build & Test

on:
  push:
    branches: ["main"]
    paths:
        - Package.swift
        - FrostSwiftFFI/**
  pull_request:
    branches: ["main"]
    branches-ignore: ["release-*.*.*"]
    paths:
        - Package.swift
        - FrostSwiftFFI/**

env: 
  CARGO_TERM_COLOR: always

jobs:
    build_and_test_swift:
        name: Rust project - latest
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v4
        - run: swift test --verbose