name: Swift Build & Test

on:
  push:
    branches: ["main"]
    paths:
        - Package.swift
        - FrostSwift/**
  pull_request:
    branches: ["main"]
    paths:
        - Package.swift
        - 'FrostSwift/**'
        - '!FrostSwift/*.md'

env: 
  CARGO_TERM_COLOR: always

jobs:
    build_and_test_swift:
        if: ${{ ! startsWith(github.event.pull_request.head.ref, 'release-') }}
        name: Build and Test Swift Package - latest
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v4
        - run: swift test --verbose